# Generated by Django 3.2.13 on 2024-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Hallticket', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('Branch', models.CharField(choices=[('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical and Electronic Engineering '), ('CE', 'civil Engineering '), ('AIML', 'Artifical Intelligence and Machine Learning'), ('DS', 'Data Science'), ('CS', 'CyberSecurity')], max_length=100)),
                ('CasteCategory', models.CharField(max_length=100)),
                ('Fathername', models.CharField(max_length=1000)),
                ('Mothername', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('profileimg', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'studentmodels',
            },
        ),
    ]
